const $=s=>document.querySelector(s);const percent=v=>`${Math.round(v*100)}%`;
const num=v=>Number(v).toFixed(1);
const time=s=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(s));
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function probGrid(parent,values,ks){const grid=el('div','probs');for(const k of ks){const c=el('div','prob');c.append(el('span','',`${k}+`),el('b','',percent(values[String(k)])));grid.append(c)}parent.append(grid)}
function mentionPanel(g){
const panel=el('section','mention');const m=g.broadcast_mention;
panel.append(el('div','eyebrow','BROADCAST · “ALLEY-OOP” MENTION'),el('strong','','Experimental booth conversion'));
if(!m||m.status==='unavailable'){panel.append(el('p','','Broadcast estimate unavailable. Count forecasts remain separate.'));return panel}
if(m.validation_status!=='unvalidated_heuristic'||m.target!=='broadcast_phrase_mention'){panel.append(el('p','','Unsupported broadcast estimate; not displayed.'));return panel}
if(m.status==='experimental_documented_booth'&&Number.isFinite(m.probability)&&m.booth){panel.append(el('div','mention-value',percent(m.probability)),el('p','',`${m.booth.crew.join(' & ')} · ${m.booth.feed_scope==='national'?'National feed':'Home local feed'}`))}
else{panel.append(el('p','','Booth not source-documented; no single game-specific mention probability.'))}
if(m.scenario_range&&Number.isFinite(m.scenario_range.min)&&Number.isFinite(m.scenario_range.max)){panel.append(el('div','mention-range',`${percent(m.scenario_range.min)}–${percent(m.scenario_range.max)} assumption sensitivity`))}
panel.append(el('p','mention-warning','These are recovered, unvalidated Arena assumptions—not calibrated probabilities, market quotes, or a confidence interval.'));
if(m.scenarios?.length){const detail=el('details','detail');detail.append(el('summary','','Compare booth assumptions'));const list=el('div','scenario-list');for(const row of m.scenarios){const line=el('div','scenario-row');line.append(el('span','',`${row.archetype.replaceAll('_',' ')} · ${row.parameter_set==='arena_freeze'?'Arena original':'Arena opening week'}`),el('b','',percent(row.probability)));list.append(line)}detail.append(list);panel.append(detail)}
return panel}
function card(g,odds){const c=el('article','card');const top=el('div','card-top');top.append(el('span','',time(g.tip_utc)),el('span','','GAME '+g.game_id));c.append(top);
const m=el('div','matchup');m.append(el('span','',g.away.abbreviation),el('span','at','@'),el('span','',g.home.abbreviation));c.append(m);
const ts=el('div','totals');for(const [label,value,cls] of [[g.away.abbreviation,g.away.expected,''],[g.home.abbreviation,g.home.expected,''],['GAME',g.total.expected,'total']]){const d=el('div',cls);d.append(el('small','',label),el('strong','',num(value)));ts.append(d)}c.append(ts);
c.append(mentionPanel(g));
c.append(el('div','subhead','Game alley-oops · probability of at least'));probGrid(c,g.total.probabilities,[1,2,3,4,5]);
const detail=el('details','detail');detail.append(el('summary','','Team probabilities & count distribution'));const teams=el('div','team-probs');for(const side of [g.away,g.home]){const panel=el('div');panel.append(el('div','subhead',side.abbreviation));probGrid(panel,side.probabilities,[1,2,3,4]);teams.append(panel)}detail.append(teams,el('div','subhead','Game total · 0, 1, 2, 3, 4, 5+'));const bars=el('div','histogram'),labels=el('div','hist-labels');for(let i=0;i<6;i++){const b=el('div','bar');b.style.height=`${Math.max(2,g.total.distribution[i]*190)}px`;b.title=`${i===5?'5+':i}: ${percent(g.total.distribution[i])}`;bars.append(b);labels.append(el('span','',i===5?'5+':String(i)))}detail.append(bars,labels);c.append(detail);
const matches=(odds.markets||[]).filter(v=>v.game_id===g.game_id&&v.market==='alley_oop'&&v.is_alley_oop===true);const note=el('div','odds');note.append(el('strong','','Alley-oop sportsbook line: '));
if(matches.length){for(const o of matches){const price=o.price_american>0?`+${o.price_american}`:o.price_american;note.append(el('div','',`${o.bookmaker}: ${o.outcome}${o.line===null||o.line===undefined?'':` ${o.line}`} (${price}) · ${time(o.retrieved_at)}`))}}else note.append(document.createTextNode(odds.source_status==='not_connected'?'Count-odds source not connected.':'No alley-oop market currently available.'));c.append(note);
const marketNote=el('div','odds');marketNote.append(el('strong','','Kalshi mention quotes: '),document.createTextNode('Not connected. Public data-display permission unresolved; no market edge calculated.'));c.append(marketNote);
c.append(el('div','card-foot',`EXP-008 · Generated ${time(g.generated_at)}`));return c}
async function load(){try{const [r,o,p]=await Promise.all([fetch('data/current.json',{cache:'no-store'}),fetch('data/odds.json',{cache:'no-store'}),fetch('data/performance.json',{cache:'no-store'})]);if(!r.ok)throw Error('Forecast file unavailable');const data=await r.json(),odds=o.ok?await o.json():{markets:[]},perf=p.ok?await p.json():{settled_games:0};const updated=new Date(data.generated_at);const old=Date.now()-updated.getTime()>45*60*1000;$('#freshness').textContent=old?'Last update may be delayed':'Forecasts current';$('#last-updated').textContent=`Last successful update ${time(data.generated_at)}`;$('#model-label').textContent=`Model ${data.model_version} · Trained through ${data.training_cutoff_date}`;$('#game-count').textContent=`${data.games.length} games`;const board=$('#board');board.replaceChildren();if(!data.games.length){const e=el('div','empty');e.append(el('strong','','No games in the next 48 hours'),document.createTextNode(data.next_scheduled_tip_utc&&!data.next_scheduled_tip_utc.includes('NaT')?` Next scheduled tip: ${time(data.next_scheduled_tip_utc)}.`:' Check back when the NBA schedule has upcoming games.'));board.append(e)}else for(const g of data.games)board.append(card(g,odds));const perfBox=$('#performance');perfBox.replaceChildren();if(perf.settled_games){perfBox.append(el('div','metric',num(perf.mae)),el('div','metric-note',`MAE · ${perf.settled_team_games} team forecasts settled`),el('p','',`P(1+) Brier score: ${num(perf.brier_p1)}${perf.rolling_30d_mae===null?'':` · Last 30 days MAE: ${num(perf.rolling_30d_mae)}`}`))}else perfBox.append(el('p','','Forward performance begins after published pregame forecasts settle. Historical backtests are not counted here.'))}catch(err){$('#board').replaceChildren(el('p','empty','Forecast data is temporarily unavailable. Last published page remains available; please check back.'));$('#freshness').textContent='Update unavailable'}}load();
